// <auto-generated />
using System;
using DetectorEstafas.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DetectorEstafas.Web.Migrations
{
    [DbContext(typeof(DetectorEstafasDbContext))]
    [Migration("20260731034631_AddCommunityReports")]
    partial class AddCommunityReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DetectorEstafas.Web.Models.AnalisisFeedback", b =>
                {
                    b.Property<long>("AnalisisRegistroId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("FueUtil")
                        .HasColumnType("bit");

                    b.HasKey("AnalisisRegistroId");

                    b.ToTable("AnalisisFeedbacks", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.AnalisisRegistro", b =>
                {
                    b.Property<long>("AnalisisRegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AnalisisRegistroId"));

                    b.Property<short>("CantidadSenales")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("NivelRiesgo")
                        .HasColumnType("int");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte>("Puntaje")
                        .HasColumnType("tinyint");

                    b.Property<int>("TipoContenido")
                        .HasColumnType("int");

                    b.HasKey("AnalisisRegistroId");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("TipoContenido", "NivelRiesgo");

                    b.ToTable("AnalisisRegistros", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ReporteComunitario", b =>
                {
                    b.Property<long>("AnalisisRegistroId")
                        .HasColumnType("bigint");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("AnalisisRegistroId");

                    b.HasIndex("Categoria");

                    b.HasIndex("FechaUtc");

                    b.ToTable("ReportesComunitarios", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.AnalisisFeedback", b =>
                {
                    b.HasOne("DetectorEstafas.Web.Models.AnalisisRegistro", null)
                        .WithOne()
                        .HasForeignKey("DetectorEstafas.Web.Models.AnalisisFeedback", "AnalisisRegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ReporteComunitario", b =>
                {
                    b.HasOne("DetectorEstafas.Web.Models.AnalisisRegistro", null)
                        .WithOne()
                        .HasForeignKey("DetectorEstafas.Web.Models.ReporteComunitario", "AnalisisRegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
