// <auto-generated />
using System;
using DetectorEstafas.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DetectorEstafas.Web.Migrations
{
    [DbContext(typeof(DetectorEstafasDbContext))]
    partial class DetectorEstafasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DetectorEstafas.Web.Models.AnalisisFeedback", b =>
                {
                    b.Property<long>("AnalisisRegistroId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("FueUtil")
                        .HasColumnType("bit");

                    b.HasKey("AnalisisRegistroId");

                    b.ToTable("AnalisisFeedbacks", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.AnalisisRegistro", b =>
                {
                    b.Property<long>("AnalisisRegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AnalisisRegistroId"));

                    b.Property<short>("CantidadSenales")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("NivelRiesgo")
                        .HasColumnType("int");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte>("Puntaje")
                        .HasColumnType("tinyint");

                    b.Property<int>("TipoContenido")
                        .HasColumnType("int");

                    b.HasKey("AnalisisRegistroId");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("TipoContenido", "NivelRiesgo");

                    b.ToTable("AnalisisRegistros", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ApiComercial.ApiClave", b =>
                {
                    b.Property<int>("ApiClaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApiClaveId"));

                    b.Property<int>("ApiClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("FechaRevocacionUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("Habilitada")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("ApiClaveId");

                    b.HasIndex("Prefijo");

                    b.HasIndex("ApiClienteId", "Habilitada");

                    b.ToTable("ApiClaves", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ApiComercial.ApiCliente", b =>
                {
                    b.Property<int>("ApiClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApiClienteId"));

                    b.Property<int>("CuotaDiaria")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ApiClienteId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ApiClientes", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ApiComercial.ApiConsumoDiario", b =>
                {
                    b.Property<long>("ApiConsumoDiarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApiConsumoDiarioId"));

                    b.Property<int>("ApiClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CantidadSolicitudes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaUtc")
                        .HasColumnType("date");

                    b.Property<DateTime>("UltimaSolicitudUtc")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("ApiConsumoDiarioId");

                    b.HasIndex("ApiClienteId", "FechaUtc")
                        .IsUnique();

                    b.ToTable("ApiConsumosDiarios", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ReporteComunitario", b =>
                {
                    b.Property<long>("AnalisisRegistroId")
                        .HasColumnType("bigint");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("AnalisisRegistroId");

                    b.HasIndex("Categoria");

                    b.HasIndex("FechaUtc");

                    b.ToTable("ReportesComunitarios", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.UsuarioAplicacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AceptoCondiciones")
                        .HasColumnType("bit");

                    b.Property<bool>("AceptoPrivacidad")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAceptacionCondicionesUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.AnalisisFeedback", b =>
                {
                    b.HasOne("DetectorEstafas.Web.Models.AnalisisRegistro", null)
                        .WithOne()
                        .HasForeignKey("DetectorEstafas.Web.Models.AnalisisFeedback", "AnalisisRegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ApiComercial.ApiClave", b =>
                {
                    b.HasOne("DetectorEstafas.Web.Models.ApiComercial.ApiCliente", "Cliente")
                        .WithMany("Claves")
                        .HasForeignKey("ApiClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ApiComercial.ApiConsumoDiario", b =>
                {
                    b.HasOne("DetectorEstafas.Web.Models.ApiComercial.ApiCliente", "Cliente")
                        .WithMany("Consumos")
                        .HasForeignKey("ApiClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ReporteComunitario", b =>
                {
                    b.HasOne("DetectorEstafas.Web.Models.AnalisisRegistro", null)
                        .WithOne()
                        .HasForeignKey("DetectorEstafas.Web.Models.ReporteComunitario", "AnalisisRegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DetectorEstafas.Web.Models.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DetectorEstafas.Web.Models.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectorEstafas.Web.Models.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DetectorEstafas.Web.Models.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DetectorEstafas.Web.Models.ApiComercial.ApiCliente", b =>
                {
                    b.Navigation("Claves");

                    b.Navigation("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
